# Generated by Django 3.0.6 on 2020-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='new_title',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='News', max_length=100),
            preserve_default=False,
        ),
    ]
