# Generated by Django 3.0.6 on 2020-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200614_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Apoorv', max_length=100),
            preserve_default=False,
        ),
    ]
