# Generated by Django 3.0.6 on 2020-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='number',
            field=models.CharField(default='+91 - 9540795011', max_length=20),
            preserve_default=False,
        ),
    ]
