# Generated by Django 3.0.6 on 2020-06-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200615_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='news',
        ),
        migrations.RemoveField(
            model_name='about',
            name='news_title',
        ),
    ]
