# Generated by Django 3.0.6 on 2020-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_report_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
