# Generated by Django 3.0.6 on 2020-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200615_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created',
            new_name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='map_snippet',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
    ]
